networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sys'
      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.26.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - user.config
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

plex:
  image: plexinc/pms-docker
  container_name: plex
  volumes:
    - /data/movies:/data/movies
    - /data/tv:/data/tv
    - /data/music:/data/music
    - /config/plex:/config
    - /transcode:/transcode
  restart: unless-stopped
  net: "host"

plexpy:
  image: linuxserver/plexpy
  container_name: plexpy
  volumes:
    - /config/plexpy:/config
    - /config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
  restart: unless-stopped
  ports:
    - 8181:8181

sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /config/sonarr:/config
    - /data/tv:/tv
    - /data/download/sabnzbd/complete/tv:/downloads
  restart: unless-stopped
  ports:
    - 8989:8989

couchpotato:
  image: linuxserver/couchpotato
  container_name: couchpotato
  volumes:
    - /config/couchpotato:/config
    - /data/download/sabnzbd/complete/movies:/downloads
    - /data/movies:/movies
  restart: unless-stopped
  ports:
    - 5050:5050

sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /config/sabnzbd:/config
      - /data/download/sabnzbd/complete:/downloads
      - /data/download/sabnzbd/incomplete:/incomplete-downloads
    restart: unless-stopped
    ports:
      - 8080:8080

deluge:
    image: linuxserver/deluge
    container_name: deluge
    volumes:
      - /data/download/deluge:/downloads
      - /config/deluge:/config
    net: "host"
    restart: unless-stopped

mylar:
  image: linuxserver/mylar
  container_name: mylar
  volumes:
    - /data/comics:/comics
    - /data/download/sabnzbd/complete/comics:/downloads
    - /config/mylar:/config/
  restart: unless-stopped
  ports:
    - 8090:8090

ubooquity:
  image: linuxserver/ubooquity
  container_name: ubooquity
  volumes:
    - /config/ubooquity:/config
    - /data/books:/books
    - /data/comics:/comics
  ports:
    - 2202:2202
    - 2203:2203
  restart: unless-stopped

calire-web:
  image: linuxserver/calibre-web
  container_name: calibre-web
  volumes:
    - /config/calibre-web:/config
    - /data/books:/books
  ports:
    - 8083:8083
  restart: unless-stopped

resilio-sync:
  image: linuxserver/resilio-sync
  container_name: resilio-sync
  volumes:
    - /config/resilio-sync:/config
    - /data/sync:/sync/folder
  restart: unless-stopped
  ports:
    - 8888:8888
    - 55555:55555

portainer:
  image: portainer/portainer
  container_name: portainer
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: unless-stopped
  ports:
    - 9000:9000

ts3:
  image: linuxserver/gsm-ts3
  container_name: gsm-ts3
  net: "host"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /config/ts3:/config
  restart: unless-stopped

openvpn-as:
  image: linuxserver/openvpn-as
  container_name: openvpn-as
  volumes:
    - /config/openvpn-as:/config
  net: "host"

watchtower:
  image: v2tec/watchtower
  container_name: watchtower
  net: "host"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: unless-stopped
